name: 'causecade'
version: 0.0.1
description: An absolute bare-bones web app.
author: Nemo Andrea nemoandrea@gmail.com
homepage: sandcrawler.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  d3: '^0.2.0'
  quiver: any

transformers:
- dart_to_js_script_rewriter
