name: 'causecade'
version: 0.0.1
description: Web based Bayesian Networks
author: Nemo Andrea nemoandrea@gmail.com
homepage: sandcrawler.github.io

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  angular2: any
  angular2_components: '^0.2.2'
  d3: '^0.2.0'
  quiver: any
  json: any
  chartjs: any

transformers:
- angular2:
    entry_points: web/main.dart
    platform_directives: 'package:angular2/common.dart#COMMON_DIRECTIVES'
- dart_to_js_script_rewriter
- $dart2js:
    minify: true