name: 'causecade'
version: 0.0.1
description: Web based Bayesian Networks
author: Nemo Andrea nemoandrea@outlook.com
homepage: sandcrawler.github.io

environment:
  sdk: '>=1.22.0'

dependencies:
  browser: '>=0.10.0'
  dart_to_js_script_rewriter: '^1.0.1'
  angular2: any
  angular_components: any
  d3: '^0.2.0'
  quiver: any
  json: any
  chartjs: any
  markdown: "^0.11.4"


transformers:
- angular2:
    entry_points: web/main.dart
    platform_directives: 'package:angular2/common.dart#COMMON_DIRECTIVES'
- dart_to_js_script_rewriter
- $dart2js:
    minify: true